[package]
name = "lumi"
edition = "2024.beta"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "framework/mainnet", override = true }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet", override = true }
CetusClmm = { r.mvr = "@cetuspackages/clmm" }

[addresses]
lumi = "0x0"
